#created by Apache Tomcat Maven plugin
#Fri Mar 22 20:35:30 BRT 2024
accessLogValveFormat=%h %l %u %t %r %s %b %I %D
connectorhttpProtocol=HTTP/1.1
enableNaming=false
generationTimestamp=1711150530857
useServerXml=false
wars=.war|/
